#!/bin/bash
# Award Radar — local daily job (runs on Sam's Mac via launchd).
# Runs from the residential IP so Awwwards + CSSDA (which block datacenter IPs)
# succeed here. Full loop: pull -> scrape+analyze all 4 sources -> commit/push
# -> rebuild static site -> redeploy to Vercel. The live link refreshes itself.
set -uo pipefail

REPO="/Users/samtipikin/Desktop/Wards"
LOG="$REPO/daily-local.log"
LOCK="$REPO/.daily-local.lock"

# launchd gives a minimal PATH — bake in nvm's node/npm/vercel/claude + git.
# NOTE: if you upgrade node via nvm, update this version path.
export PATH="/Users/samtipikin/.nvm/versions/node/v22.17.0/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# Link the Vercel deploy to the award-radar project without a .vercel dir
# (the web/out folder is regenerated by each build).
export VERCEL_ORG_ID="team_LtPAy9qU6NXqa6cmMVvnFLxp"
export VERCEL_PROJECT_ID="prj_rKVFfWiD5ykfcbvGMTAuulzgHNHh"

# Atomic lock (mkdir is atomic; macOS has no flock). Skip if already running.
if ! mkdir "$LOCK" 2>/dev/null; then
  echo "[$(date)] another run holds the lock; skipping" >> "$LOG"
  exit 0
fi
trap 'rmdir "$LOCK" 2>/dev/null' EXIT

{
  echo ""
  echo "======================================================"
  echo "[$(date)] daily-local starting"
  cd "$REPO" || { echo "cd failed"; exit 1; }

  # 1. Pull any commits (e.g. from the GitHub Actions run) before scraping.
  git pull --no-edit || echo "git pull failed (continuing)"

  # 2. Scrape all sources + analyze new winners (idempotent upserts).
  npm run run || echo "pipeline reported failures (continuing)"

  # 3. Commit + push the updated data. If the remote moved, keep our DB.
  git add data/
  if git diff --staged --quiet; then
    echo "no data changes to commit"
  else
    git commit -m "data: $(date -u +%F) (local)"
    if ! git push; then
      echo "push rejected; merging remote (keeping local DB) and retrying"
      git fetch origin && git merge -X ours --no-edit origin/main && git push
    fi
  fi

  # 4. Rebuild the static site with the fresh data.
  ( cd web && npm run build ) || { echo "web build failed"; exit 1; }

  # 5. Redeploy the prebuilt static output to Vercel production.
  ( cd web/out && vercel deploy --prod --yes ) && echo "redeployed to Vercel"

  echo "[$(date)] daily-local done"
} >> "$LOG" 2>&1
